### PR TITLE
Use non-deprecated checkhealth syntax

### PR DESCRIPTION
**Pull request by dundargoc**

### CODE REVIEW

**Review by yriveiro — APPROVED** [review]

**Comment by dundargoc** [comment]
Stylua failure probably unrelated; you need to upgrade to version 3 of the action.

**Comment by yriveiro** [comment]
> Stylua failure probably unrelated; you need to upgrade to version 3 of the action.

I did a PR bumping action version, could you rebase this PR on top of it?

**Comment by dundargoc** [comment]
Done.

**Comment by yriveiro** [comment]
Thanks for your contribution @dundargoc

**Pull request merged**
